name: Automated Test

on:
  push:
    branches:
      - main

jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Produce actual.txt output
        run: python3 find_lowest_number/find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt
      
      - name: Compare expected output to actual
        run: diff test_data/test1_actual.txt test_data/test1_expected.txt
