name: Automated Test

on:
  push:
    branches:
      - main

jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Produce actual.txt output for test1
        run: python3 find_lowest_number/find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt
      
      - name: Compare expected output to actual for test1
        run: diff test_data/test1_actual.txt test_data/test1_expected.txt

      - name: Produce actual.txt output for test2
        run: python3 find_lowest_number/find_lowest_number.py test_data/test2_input.txt test_data/test2_actual.txt
      
      - name: Compare expected output to actual for test2
        run: diff test_data/test2_actual.txt test_data/test2_expected.txt

      - name: Produce actual.txt output for test3
        run: python3 find_lowest_number/find_lowest_number.py test_data/test3_input.txt test_data/test3_actual.txt
      
      - name: Compare expected output to actual for test3
        run: diff test_data/test3_actual.txt test_data/test3_expected.txt
