name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Test Case 1
      - name: Run Test Case 1
        run: python3 find_lowest_number/find_lowest_number.py test_data/test1_input.txt test_data/test1_actual.txt
      - name: Diff Test Case 1
        run: diff test_data/test1_actual.txt test_data/test1_expected.txt
        
      # Test Case 2
      - name: Run Test Case 2
        run: python3 find_lowest_number/find_lowest_number.py test_data/test2_input.txt test_data/test2_actual.txt
      - name: Diff Test Case 2
        run: diff test_data/test2_actual.txt test_data/test2_expected.txt
        
      # Test Case 3
      - name: Run Test Case 3
        run: python3 find_lowest_number/find_lowest_number.py test_data/test3_input.txt test_data/test3_actual.txt
      - name: Diff Test Case 3
        run: diff test_data/test3_actual.txt test_data/test3_expected.txt
